name: Echo Sharp CI

on:
  push:
    branches:
      test/echo-sharp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a set of commands using the runners shell
      - name: Echo
        run: |
          echo \#
          
