# This is a basic workflow to help you get started with Actions

name: Test CI

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a set of commands using the runners shell
      - name: Print date
        run: |
          echo $(date '+%Y-%m-%d %H:%M:%S(%z)')
          echo $(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S(%z)')
