# This is a basic workflow to help you get started with Actions

name: Test CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          ./scripts/tz.sh
