# タイムゾーン検証用CI
name: Timezone CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "50 13 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  execute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: test/timezone-2

      # Runs a set of commands using the runners shell
      - name: Print date
        run: |
          echo $(date '+%Y-%m-%d %H:%M:%S')
          echo $(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S')
